name: quetz
channels:
  - https://repo.mamba.pm/conda-forge
dependencies:
  - python>=3.7
  - pip
  - fastapi
  - typer
  - authlib=0.15.5
  - psycopg2
  - httpx=0.20.0
  - sqlalchemy
  - sqlalchemy-utils
  - sqlite
  - python-multipart
  - uvicorn
  - zstandard
  - conda-build
  - appdirs
  - toml
  - fsspec
  - requests
  - h2
  - pluggy
  - jinja2
  - itsdangerous
  - alembic
  - zchunk
  - s3fs
  - gcsfs >=2022.03
  - sphinx
  - sphinx-book-theme
  - tenacity
  - xattr
  - aiofiles
  - pyyaml
  - ujson
  - prometheus_client
  - pamela
  - typing_extensions
  - adlfs
  - importlib_metadata
