name: quetz
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - fastapi
  - typer
  - authlib
  - psycopg2
  - httpx=0.16.0
  - sqlalchemy
  - sqlalchemy-utils
  - sqlite
  - python-multipart
  - uvicorn
  - zstandard
  - conda-build
  - appdirs
  - toml
  - quetz-client
  - fsspec
  - requests
  - h2<4.0.0
  - pluggy
  - starlette-full
  - jinja2
  - itsdangerous
  - alembic
  - zchunk
  - s3fs
  - sphinx
  - sphinx-book-theme
  - tenacity
  - xattr